// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
  /**
   * hero_image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * hero_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * challenge_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.challenge_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_title: prismic.RichTextField;

  /**
   * challenge_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.challenge_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_content: prismic.RichTextField;

  /**
   * solution_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.solution_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_title: prismic.RichTextField;

  /**
   * solution_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.solution_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_content: prismic.RichTextField;

  /**
   * impact_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.impact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_title: prismic.RichTextField;

  /**
   * impact_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.impact_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_content: prismic.RichTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

type HomepageDocumentDataBodySlice =
  | HerosectionSlice
  | ExpertisegroupSlice
  | ExpertiseareasSlice
  | ServiceGridSlice
  | ImageandtextSlice
  | ProcessSlice
  | ProjectShowcaseSlice
  | FaqSlice
  | ContactSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

interface LandingPageDocumentData {}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Layout → header_navigation*
 */
export interface LayoutDocumentDataHeaderNavigationItem {
  /**
   * link_label field in *Layout → header_navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * link_object field in *Layout → header_navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[].link_object
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_object: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Layout → footer_quick_links*
 */
export interface LayoutDocumentDataFooterQuickLinksItem {
  /**
   * link_label field in *Layout → footer_quick_links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * link_object field in *Layout → footer_quick_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[].link_object
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_object: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * header_logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * header_cta_label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  header_cta_label: prismic.KeyTextField;

  /**
   * header_cta_link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  header_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * header_navigation field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  header_navigation: prismic.GroupField<
    Simplify<LayoutDocumentDataHeaderNavigationItem>
  >;

  /**
   * footer_company_name field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_company_name: prismic.RichTextField;

  /**
   * footer_tagline field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_tagline: prismic.RichTextField;

  /**
   * footer_quick_links_title field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_quick_links_title: prismic.RichTextField;

  /**
   * footer_quick_links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_quick_links: prismic.GroupField<
    Simplify<LayoutDocumentDataFooterQuickLinksItem>
  >;

  /**
   * footer_contact_title field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_contact_title: prismic.RichTextField;

  /**
   * footer_email field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_email: prismic.KeyTextField;

  /**
   * footer_phone field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_phone: prismic.KeyTextField;

  /**
   * footer_address field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_address: prismic.RichTextField;

  /**
   * footer_copyright_text field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_copyright_text: prismic.RichTextField;

  /**
   * footer_privacy_policy_link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_privacy_policy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_privacy_policy_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * title field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * page_content field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.page_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_content: prismic.RichTextField;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

type TeamPageDocumentDataBodySlice = never;

type TeamPageDocumentDataBody1Slice = TeamHeroSlice;

type TeamPageDocumentDataBody2Slice = TeamMembersSlice;

/**
 * Content for Team Page documents
 */
interface TeamPageDocumentData {
  /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<TeamPageDocumentDataBodySlice> /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body1[]
   * - **Tab**: Team Hero
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  body1: prismic.SliceZone<TeamPageDocumentDataBody1Slice> /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body2[]
   * - **Tab**: Team Members
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  body2: prismic.SliceZone<TeamPageDocumentDataBody2Slice>;
}

/**
 * Team Page document from Prismic
 *
 * - **API ID**: `team_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeamPageDocumentData>,
    "team_page",
    Lang
  >;

export type AllDocumentTypes =
  | CaseStudyDocument
  | HomepageDocument
  | LandingPageDocument
  | LayoutDocument
  | PrivacyPolicyDocument
  | TeamPageDocument;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * main_title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.main_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_title: prismic.RichTextField;

  /**
   * subtitle field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * info_title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.info_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  info_title: prismic.RichTextField;

  /**
   * hours_title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.hours_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hours_title: prismic.RichTextField;

  /**
   * form_title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * full_name_label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.full_name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  full_name_label: prismic.KeyTextField;

  /**
   * email_label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * company_label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.company_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_label: prismic.KeyTextField;

  /**
   * budget_label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.budget_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  budget_label: prismic.KeyTextField;

  /**
   * goals_label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.goals_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  goals_label: prismic.KeyTextField;

  /**
   * button_label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * budget_options field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.budget_options
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  budget_options: prismic.KeyTextField;

  /**
   * section_id field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *Contact → Items*
 */
export interface ContactSliceDefaultItem {
  /**
   * item_type field in *Contact → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].item_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  item_type: prismic.SelectField<
    "Contact Info" | "Office Hour" | "Contact Form"
  >;

  /**
   * icon_name field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * info_item_title field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].info_item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info_item_title: prismic.KeyTextField;

  /**
   * info_item_description field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].info_item_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info_item_description: prismic.KeyTextField;

  /**
   * days field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].days
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  days: prismic.KeyTextField;

  /**
   * hours field in *Contact → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].hours
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hours: prismic.KeyTextField;

  /**
   * is_closed field in *Contact → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: Contact.items[].is_closed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_closed: prismic.BooleanField;

  /**
   * link_type field in *Contact → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: Contact.items[].link_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  link_type: prismic.SelectField<"None" | "Email" | "Phone">;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  Simplify<ContactSliceDefaultItem>
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `Contact`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "Contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Expertiseareas → Default → Primary*
 */
export interface ExpertiseareasSliceDefaultPrimary {
  /**
   * heading field in *Expertiseareas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Expertiseareas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;
}

/**
 * Primary content in *Expertiseareas → Items*
 */
export interface ExpertiseareasSliceDefaultItem {
  /**
   * icon_name field in *Expertiseareas → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * item_title field in *Expertiseareas → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * item_description field in *Expertiseareas → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Default variation for Expertiseareas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseareasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExpertiseareasSliceDefaultPrimary>,
  Simplify<ExpertiseareasSliceDefaultItem>
>;

/**
 * Slice variation for *Expertiseareas*
 */
type ExpertiseareasSliceVariation = ExpertiseareasSliceDefault;

/**
 * Expertiseareas Shared Slice
 *
 * - **API ID**: `Expertiseareas`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseareasSlice = prismic.SharedSlice<
  "Expertiseareas",
  ExpertiseareasSliceVariation
>;

/**
 * Primary content in *Expertisegroup → Items*
 */
export interface ExpertisegroupSliceDefaultItem {
  /**
   * icon_name field in *Expertisegroup → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertisegroup.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * title field in *Expertisegroup → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertisegroup.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Expertisegroup → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertisegroup.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Expertisegroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertisegroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ExpertisegroupSliceDefaultItem>
>;

/**
 * Slice variation for *Expertisegroup*
 */
type ExpertisegroupSliceVariation = ExpertisegroupSliceDefault;

/**
 * Expertisegroup Shared Slice
 *
 * - **API ID**: `Expertisegroup`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertisegroupSlice = prismic.SharedSlice<
  "Expertisegroup",
  ExpertisegroupSliceVariation
>;

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * question field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Faq.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `Faq`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"Faq", FaqSliceVariation>;

/**
 * Primary content in *Herosection → Default → Primary*
 */
export interface HerosectionSliceDefaultPrimary {
  /**
   * hero_title_part1 field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.hero_title_part1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title_part1: prismic.RichTextField;

  /**
   * hero_title_part2 field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.hero_title_part2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title_part2: prismic.RichTextField;

  /**
   * hero_description field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * button_1_link field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.button_1_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button_1_label field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.button_1_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_1_label: prismic.KeyTextField;

  /**
   * background_image field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Herosection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HerosectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HerosectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Herosection*
 */
type HerosectionSliceVariation = HerosectionSliceDefault;

/**
 * Herosection Shared Slice
 *
 * - **API ID**: `Herosection`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HerosectionSlice = prismic.SharedSlice<
  "Herosection",
  HerosectionSliceVariation
>;

/**
 * Primary content in *Imageandtext → Default → Primary*
 */
export interface ImageandtextSliceDefaultPrimary {
  /**
   * image field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Imageandtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageandtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageandtextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Imageandtext*
 */
type ImageandtextSliceVariation = ImageandtextSliceDefault;

/**
 * Imageandtext Shared Slice
 *
 * - **API ID**: `Imageandtext`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageandtextSlice = prismic.SharedSlice<
  "Imageandtext",
  ImageandtextSliceVariation
>;

/**
 * Primary content in *Process → Default → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * title field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Process → Items*
 */
export interface ProcessSliceDefaultItem {
  /**
   * icon_text field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].icon_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_text: prismic.KeyTextField;

  /**
   * item_title field in *Process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * weeks field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].weeks
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  weeks: prismic.KeyTextField;

  /**
   * item_description field in *Process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  Simplify<ProcessSliceDefaultItem>
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `Process`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSlice = prismic.SharedSlice<
  "Process",
  ProcessSliceVariation
>;

/**
 * Primary content in *ProjectShowcase → Default → Primary*
 */
export interface ProjectShowcaseSliceDefaultPrimary {
  /**
   * title field in *ProjectShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * section_id field in *ProjectShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectShowcase → Items*
 */
export interface ProjectShowcaseSliceDefaultItem {
  /**
   * project_image field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * project_title field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_title: prismic.RichTextField;

  /**
   * project_description field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * project_link field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * tags field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].tags
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tags: prismic.KeyTextField;
}

/**
 * Default variation for ProjectShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectShowcaseSliceDefaultPrimary>,
  Simplify<ProjectShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectShowcase*
 */
type ProjectShowcaseSliceVariation = ProjectShowcaseSliceDefault;

/**
 * ProjectShowcase Shared Slice
 *
 * - **API ID**: `ProjectShowcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSlice = prismic.SharedSlice<
  "ProjectShowcase",
  ProjectShowcaseSliceVariation
>;

/**
 * Primary content in *ServiceGrid → Default → Primary*
 */
export interface ServiceGridSliceDefaultPrimary {
  /**
   * title field in *ServiceGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * columns field in *ServiceGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4
   * - **API ID Path**: ServiceGrid.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * section_id field in *ServiceGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceGrid → Items*
 */
export interface ServiceGridSliceDefaultItem {
  /**
   * item_title field in *ServiceGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * icon_name field in *ServiceGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * item_description field in *ServiceGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;

  /**
   * icon_background_color field in *ServiceGrid → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].icon_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  icon_background_color: prismic.ColorField;
}

/**
 * Default variation for ServiceGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceGridSliceDefaultPrimary>,
  Simplify<ServiceGridSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceGrid*
 */
type ServiceGridSliceVariation = ServiceGridSliceDefault;

/**
 * ServiceGrid Shared Slice
 *
 * - **API ID**: `ServiceGrid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceGridSlice = prismic.SharedSlice<
  "ServiceGrid",
  ServiceGridSliceVariation
>;

/**
 * Primary content in *TeamHero → Default → Primary*
 */
export interface TeamHeroSliceDefaultPrimary {
  /**
   * Title field in *TeamHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main heading for the team page
   * - **API ID Path**: TeamHero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TeamHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Team page description paragraph
   * - **API ID Path**: TeamHero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for TeamHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamHero*
 */
type TeamHeroSliceVariation = TeamHeroSliceDefault;

/**
 * TeamHero Shared Slice
 *
 * - **API ID**: `TeamHero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamHeroSlice = prismic.SharedSlice<
  "TeamHero",
  TeamHeroSliceVariation
>;

/**
 * Primary content in *TeamMembers → Items*
 */
export interface TeamMembersSliceDefaultItem {
  /**
   * Name field in *TeamMembers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's full name
   * - **API ID Path**: TeamMembers.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *TeamMembers → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's job title/position
   * - **API ID Path**: TeamMembers.items[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Image field in *TeamMembers → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: TeamMembers.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Bio field in *TeamMembers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short biography or introduction
   * - **API ID Path**: TeamMembers.items[].bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Details field in *TeamMembers → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed achievements/background (separate each point with a new line)
   * - **API ID Path**: TeamMembers.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;

  /**
   * LinkedIn URL field in *TeamMembers → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn profile URL (optional)
   * - **API ID Path**: TeamMembers.items[].linkedin_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Twitter URL field in *TeamMembers → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Twitter profile URL (optional)
   * - **API ID Path**: TeamMembers.items[].twitter_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  twitter_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *TeamMembers → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub profile URL (optional)
   * - **API ID Path**: TeamMembers.items[].github_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for TeamMembers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMembersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TeamMembersSliceDefaultItem>
>;

/**
 * Slice variation for *TeamMembers*
 */
type TeamMembersSliceVariation = TeamMembersSliceDefault;

/**
 * TeamMembers Shared Slice
 *
 * - **API ID**: `TeamMembers`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamMembersSlice = prismic.SharedSlice<
  "TeamMembers",
  TeamMembersSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CaseStudyDocument,
      CaseStudyDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBodySlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataHeaderNavigationItem,
      LayoutDocumentDataFooterQuickLinksItem,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      TeamPageDocument,
      TeamPageDocumentData,
      TeamPageDocumentDataBodySlice,
      TeamPageDocumentDataBody1Slice,
      TeamPageDocumentDataBody2Slice,
      AllDocumentTypes,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceDefaultItem,
      ContactSliceVariation,
      ContactSliceDefault,
      ExpertiseareasSlice,
      ExpertiseareasSliceDefaultPrimary,
      ExpertiseareasSliceDefaultItem,
      ExpertiseareasSliceVariation,
      ExpertiseareasSliceDefault,
      ExpertisegroupSlice,
      ExpertisegroupSliceDefaultItem,
      ExpertisegroupSliceVariation,
      ExpertisegroupSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      HerosectionSlice,
      HerosectionSliceDefaultPrimary,
      HerosectionSliceVariation,
      HerosectionSliceDefault,
      ImageandtextSlice,
      ImageandtextSliceDefaultPrimary,
      ImageandtextSliceVariation,
      ImageandtextSliceDefault,
      ProcessSlice,
      ProcessSliceDefaultPrimary,
      ProcessSliceDefaultItem,
      ProcessSliceVariation,
      ProcessSliceDefault,
      ProjectShowcaseSlice,
      ProjectShowcaseSliceDefaultPrimary,
      ProjectShowcaseSliceDefaultItem,
      ProjectShowcaseSliceVariation,
      ProjectShowcaseSliceDefault,
      ServiceGridSlice,
      ServiceGridSliceDefaultPrimary,
      ServiceGridSliceDefaultItem,
      ServiceGridSliceVariation,
      ServiceGridSliceDefault,
      TeamHeroSlice,
      TeamHeroSliceDefaultPrimary,
      TeamHeroSliceVariation,
      TeamHeroSliceDefault,
      TeamMembersSlice,
      TeamMembersSliceDefaultItem,
      TeamMembersSliceVariation,
      TeamMembersSliceDefault,
    };
  }
}
