// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
  /**
   * hero_image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * hero_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * challenge_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.challenge_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_title: prismic.RichTextField;

  /**
   * challenge_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.challenge_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_content: prismic.RichTextField;

  /**
   * solution_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.solution_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_title: prismic.RichTextField;

  /**
   * solution_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.solution_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_content: prismic.RichTextField;

  /**
   * impact_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.impact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_title: prismic.RichTextField;

  /**
   * impact_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.impact_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_content: prismic.RichTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

type CaseStudySmDocumentDataSlicesSlice =
  | CaseStudyTextPanelSlice
  | CompactHeroSlice;

/**
 * Content for Case Study SM documents
 */
interface CaseStudySmDocumentData {
  /**
   * Slice Zone field in *Case Study SM*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_sm.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CaseStudySmDocumentDataSlicesSlice> /**
   * Meta Title field in *Case Study SM*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: case_study_sm.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Case Study SM*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case_study_sm.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Case Study SM*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_sm.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Case Study SM document from Prismic
 *
 * - **API ID**: `case_study_sm`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudySmDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudySmDocumentData>,
    "case_study_sm",
    Lang
  >;

/**
 * Primary content in *Homepage → Slice zone → Hero → Primary*
 */
export interface HomepageDocumentDataBodyHerosectionSlicePrimary {
  /**
   * hero_title_part1 field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].herosection.primary.hero_title_part1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title_part1: prismic.RichTextField;

  /**
   * hero_title_part2 field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].herosection.primary.hero_title_part2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title_part2: prismic.RichTextField;

  /**
   * hero_description field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].herosection.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * button_1_link field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].herosection.primary.button_1_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button_1_label field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].herosection.primary.button_1_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_1_label: prismic.KeyTextField;

  /**
   * background_image field in *Homepage → Slice zone → Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].herosection.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyHerosectionSlice = prismic.Slice<
  "herosection",
  Simplify<HomepageDocumentDataBodyHerosectionSlicePrimary>,
  never
>;

/**
 * Item content in *Homepage → Slice zone → CoreExpertise → Items*
 */
export interface HomepageDocumentDataBodyExpertisegroupSliceItem {
  /**
   * icon_name field in *Homepage → Slice zone → CoreExpertise → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertisegroup.items.icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * title field in *Homepage → Slice zone → CoreExpertise → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertisegroup.items.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Homepage → Slice zone → CoreExpertise → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertisegroup.items.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyExpertisegroupSlice = prismic.Slice<
  "expertisegroup",
  Record<string, never>,
  Simplify<HomepageDocumentDataBodyExpertisegroupSliceItem>
>;

/**
 * Primary content in *Homepage → Slice zone → ExpertiseAreas → Primary*
 */
export interface HomepageDocumentDataBodyExpertiseareasSlicePrimary {
  /**
   * heading field in *Homepage → Slice zone → ExpertiseAreas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertiseareas.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Homepage → Slice zone → ExpertiseAreas → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertiseareas.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;
}

/**
 * Item content in *Homepage → Slice zone → ExpertiseAreas → Items*
 */
export interface HomepageDocumentDataBodyExpertiseareasSliceItem {
  /**
   * icon_name field in *Homepage → Slice zone → ExpertiseAreas → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertiseareas.items.icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * item_title field in *Homepage → Slice zone → ExpertiseAreas → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertiseareas.items.item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * item_description field in *Homepage → Slice zone → ExpertiseAreas → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].expertiseareas.items.item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyExpertiseareasSlice = prismic.Slice<
  "expertiseareas",
  Simplify<HomepageDocumentDataBodyExpertiseareasSlicePrimary>,
  Simplify<HomepageDocumentDataBodyExpertiseareasSliceItem>
>;

/**
 * Primary content in *Homepage → Slice zone → service_grid → Primary*
 */
export interface HomepageDocumentDataBodyServiceGridSlicePrimary {
  /**
   * title field in *Homepage → Slice zone → service_grid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].service_grid.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * columns field in *Homepage → Slice zone → service_grid → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4
   * - **API ID Path**: homepage.body[].service_grid.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * section_id field in *Homepage → Slice zone → service_grid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].service_grid.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice zone → service_grid → Items*
 */
export interface HomepageDocumentDataBodyServiceGridSliceItem {
  /**
   * item_title field in *Homepage → Slice zone → service_grid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].service_grid.items.item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * icon_name field in *Homepage → Slice zone → service_grid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].service_grid.items.icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * item_description field in *Homepage → Slice zone → service_grid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].service_grid.items.item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;

  /**
   * icon_background_color field in *Homepage → Slice zone → service_grid → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].service_grid.items.icon_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  icon_background_color: prismic.ColorField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyServiceGridSlice = prismic.Slice<
  "service_grid",
  Simplify<HomepageDocumentDataBodyServiceGridSlicePrimary>,
  Simplify<HomepageDocumentDataBodyServiceGridSliceItem>
>;

/**
 * Primary content in *Homepage → Slice zone → ImageAndText → Primary*
 */
export interface HomepageDocumentDataBodyImageandtextSlicePrimary {
  /**
   * image field in *Homepage → Slice zone → ImageAndText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].imageandtext.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Homepage → Slice zone → ImageAndText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].imageandtext.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *Homepage → Slice zone → ImageAndText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].imageandtext.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *Homepage → Slice zone → ImageAndText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].imageandtext.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyImageandtextSlice = prismic.Slice<
  "imageandtext",
  Simplify<HomepageDocumentDataBodyImageandtextSlicePrimary>,
  never
>;

/**
 * Primary content in *Homepage → Slice zone → process → Primary*
 */
export interface HomepageDocumentDataBodyProcessSlicePrimary {
  /**
   * title field in *Homepage → Slice zone → process → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].process.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Item content in *Homepage → Slice zone → process → Items*
 */
export interface HomepageDocumentDataBodyProcessSliceItem {
  /**
   * icon_text field in *Homepage → Slice zone → process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].process.items.icon_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_text: prismic.KeyTextField;

  /**
   * item_title field in *Homepage → Slice zone → process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].process.items.item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * weeks field in *Homepage → Slice zone → process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].process.items.weeks
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  weeks: prismic.KeyTextField;

  /**
   * item_description field in *Homepage → Slice zone → process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].process.items.item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyProcessSlice = prismic.Slice<
  "process",
  Simplify<HomepageDocumentDataBodyProcessSlicePrimary>,
  Simplify<HomepageDocumentDataBodyProcessSliceItem>
>;

/**
 * Primary content in *Homepage → Slice zone → project_showcase → Primary*
 */
export interface HomepageDocumentDataBodyProjectShowcaseSlicePrimary {
  /**
   * title field in *Homepage → Slice zone → project_showcase → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * section_id field in *Homepage → Slice zone → project_showcase → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Item content in *Homepage → Slice zone → project_showcase → Items*
 */
export interface HomepageDocumentDataBodyProjectShowcaseSliceItem {
  /**
   * project_image field in *Homepage → Slice zone → project_showcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.items.project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * project_title field in *Homepage → Slice zone → project_showcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.items.project_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_title: prismic.RichTextField;

  /**
   * project_description field in *Homepage → Slice zone → project_showcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.items.project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * project_link field in *Homepage → Slice zone → project_showcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.items.project_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * tags field in *Homepage → Slice zone → project_showcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].project_showcase.items.tags
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tags: prismic.KeyTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyProjectShowcaseSlice = prismic.Slice<
  "project_showcase",
  Simplify<HomepageDocumentDataBodyProjectShowcaseSlicePrimary>,
  Simplify<HomepageDocumentDataBodyProjectShowcaseSliceItem>
>;

/**
 * Primary content in *Homepage → Slice zone → faq → Primary*
 */
export interface HomepageDocumentDataBodyFaqSlicePrimary {
  /**
   * title field in *Homepage → Slice zone → faq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].faq.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Item content in *Homepage → Slice zone → faq → Items*
 */
export interface HomepageDocumentDataBodyFaqSliceItem {
  /**
   * question field in *Homepage → Slice zone → faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].faq.items.question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Homepage → Slice zone → faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[].faq.items.answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Slice for *Homepage → Slice zone*
 */
export type HomepageDocumentDataBodyFaqSlice = prismic.Slice<
  "faq",
  Simplify<HomepageDocumentDataBodyFaqSlicePrimary>,
  Simplify<HomepageDocumentDataBodyFaqSliceItem>
>;

type HomepageDocumentDataBodySlice =
  | HomepageDocumentDataBodyHerosectionSlice
  | HomepageDocumentDataBodyExpertisegroupSlice
  | HomepageDocumentDataBodyExpertiseareasSlice
  | HomepageDocumentDataBodyServiceGridSlice
  | HomepageDocumentDataBodyImageandtextSlice
  | HomepageDocumentDataBodyProcessSlice
  | HomepageDocumentDataBodyProjectShowcaseSlice
  | HomepageDocumentDataBodyFaqSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

interface LandingPageDocumentData {}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Layout → header_navigation*
 */
export interface LayoutDocumentDataHeaderNavigationItem {
  /**
   * link_label field in *Layout → header_navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * link_object field in *Layout → header_navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[].link_object
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_object: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Layout → footer_quick_links*
 */
export interface LayoutDocumentDataFooterQuickLinksItem {
  /**
   * link_label field in *Layout → footer_quick_links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * link_object field in *Layout → footer_quick_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[].link_object
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_object: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * header_logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * header_cta_label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  header_cta_label: prismic.KeyTextField;

  /**
   * header_cta_link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  header_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * header_navigation field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  header_navigation: prismic.GroupField<
    Simplify<LayoutDocumentDataHeaderNavigationItem>
  >;

  /**
   * footer_company_name field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_company_name: prismic.RichTextField;

  /**
   * footer_tagline field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_tagline: prismic.RichTextField;

  /**
   * footer_quick_links_title field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_quick_links_title: prismic.RichTextField;

  /**
   * footer_quick_links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_quick_links: prismic.GroupField<
    Simplify<LayoutDocumentDataFooterQuickLinksItem>
  >;

  /**
   * footer_contact_title field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_contact_title: prismic.RichTextField;

  /**
   * footer_email field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_email: prismic.KeyTextField;

  /**
   * footer_phone field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_phone: prismic.KeyTextField;

  /**
   * footer_address field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_address: prismic.RichTextField;

  /**
   * footer_copyright_text field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_copyright_text: prismic.RichTextField;

  /**
   * footer_privacy_policy_link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_privacy_policy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_privacy_policy_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type MainpageDocumentDataSlicesSlice =
  | ContactSlice
  | WebsiteCardSlice
  | HeroSlice;

/**
 * Content for Mainpage documents
 */
interface MainpageDocumentData {
  /**
   * Slice Zone field in *Mainpage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MainpageDocumentDataSlicesSlice> /**
   * Meta Title field in *Mainpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mainpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Mainpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mainpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Mainpage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Mainpage document from Prismic
 *
 * - **API ID**: `mainpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MainpageDocumentData>,
    "mainpage",
    Lang
  >;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * title field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * page_content field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.page_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_content: prismic.RichTextField;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

type TeamPageDocumentDataBodySlice = never;

/**
 * Primary content in *Team Page → Slice zone → team_hero → Primary*
 */
export interface TeamPageDocumentDataBody1TeamHeroSlicePrimary {
  /**
   * Title field in *Team Page → Slice zone → team_hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main heading for the team page
   * - **API ID Path**: team_page.body1[].team_hero.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Team Page → Slice zone → team_hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Team page description paragraph
   * - **API ID Path**: team_page.body1[].team_hero.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Slice for *Team Page → Slice zone*
 */
export type TeamPageDocumentDataBody1TeamHeroSlice = prismic.Slice<
  "team_hero",
  Simplify<TeamPageDocumentDataBody1TeamHeroSlicePrimary>,
  never
>;

type TeamPageDocumentDataBody1Slice = TeamPageDocumentDataBody1TeamHeroSlice;

/**
 * Item content in *Team Page → Slice zone → team_members → Items*
 */
export interface TeamPageDocumentDataBody2TeamMembersSliceItem {
  /**
   * Name field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's full name
   * - **API ID Path**: team_page.body2[].team_members.items.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's job title/position
   * - **API ID Path**: team_page.body2[].team_members.items.role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Image field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body2[].team_members.items.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Bio field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short biography or introduction
   * - **API ID Path**: team_page.body2[].team_members.items.bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Details field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed achievements/background (separate each point with a new line)
   * - **API ID Path**: team_page.body2[].team_members.items.details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;

  /**
   * LinkedIn URL field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn profile URL (optional)
   * - **API ID Path**: team_page.body2[].team_members.items.linkedin_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Twitter URL field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Twitter profile URL (optional)
   * - **API ID Path**: team_page.body2[].team_members.items.twitter_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  twitter_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub profile URL (optional)
   * - **API ID Path**: team_page.body2[].team_members.items.github_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Slice for *Team Page → Slice zone*
 */
export type TeamPageDocumentDataBody2TeamMembersSlice = prismic.Slice<
  "team_members",
  Record<string, never>,
  Simplify<TeamPageDocumentDataBody2TeamMembersSliceItem>
>;

type TeamPageDocumentDataBody2Slice = TeamPageDocumentDataBody2TeamMembersSlice;

/**
 * Content for Team Page documents
 */
interface TeamPageDocumentData {
  /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<TeamPageDocumentDataBodySlice> /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body1[]
   * - **Tab**: Team Hero
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  body1: prismic.SliceZone<TeamPageDocumentDataBody1Slice> /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body2[]
   * - **Tab**: Team Members
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  body2: prismic.SliceZone<TeamPageDocumentDataBody2Slice>;
}

/**
 * Team Page document from Prismic
 *
 * - **API ID**: `team_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeamPageDocumentData>,
    "team_page",
    Lang
  >;

export type AllDocumentTypes =
  | CaseStudyDocument
  | CaseStudySmDocument
  | HomepageDocument
  | LandingPageDocument
  | LayoutDocument
  | MainpageDocument
  | PrivacyPolicyDocument
  | TeamPageDocument;

/**
 * Primary content in *CaseStudyTextPanel → Challenge → Primary*
 */
export interface CaseStudyTextPanelSliceDefaultPrimary {
  /**
   * challenge_title field in *CaseStudyTextPanel → Challenge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.default.primary.challenge_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_title: prismic.RichTextField;

  /**
   * challenge_content field in *CaseStudyTextPanel → Challenge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.default.primary.challenge_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_content: prismic.RichTextField;
}

/**
 * Challenge variation for CaseStudyTextPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudyTextPanelSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CaseStudyTextPanel → Solution Text Panel → Primary*
 */
export interface CaseStudyTextPanelSliceSolutionTextPanelPrimary {
  /**
   * solution_title field in *CaseStudyTextPanel → Solution Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.solutionTextPanel.primary.solution_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_title: prismic.RichTextField;

  /**
   * solution_content field in *CaseStudyTextPanel → Solution Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.solutionTextPanel.primary.solution_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_content: prismic.RichTextField;
}

/**
 * Solution Text Panel variation for CaseStudyTextPanel Slice
 *
 * - **API ID**: `solutionTextPanel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSliceSolutionTextPanel =
  prismic.SharedSliceVariation<
    "solutionTextPanel",
    Simplify<CaseStudyTextPanelSliceSolutionTextPanelPrimary>,
    never
  >;

/**
 * Primary content in *CaseStudyTextPanel → Impact Text Panel → Primary*
 */
export interface CaseStudyTextPanelSliceImpactTextPanelPrimary {
  /**
   * impact_title field in *CaseStudyTextPanel → Impact Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.impactTextPanel.primary.impact_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_title: prismic.RichTextField;

  /**
   * impact_content field in *CaseStudyTextPanel → Impact Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.impactTextPanel.primary.impact_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_content: prismic.RichTextField;
}

/**
 * Impact Text Panel variation for CaseStudyTextPanel Slice
 *
 * - **API ID**: `impactTextPanel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSliceImpactTextPanel =
  prismic.SharedSliceVariation<
    "impactTextPanel",
    Simplify<CaseStudyTextPanelSliceImpactTextPanelPrimary>,
    never
  >;

/**
 * Slice variation for *CaseStudyTextPanel*
 */
type CaseStudyTextPanelSliceVariation =
  | CaseStudyTextPanelSliceDefault
  | CaseStudyTextPanelSliceSolutionTextPanel
  | CaseStudyTextPanelSliceImpactTextPanel;

/**
 * CaseStudyTextPanel Shared Slice
 *
 * - **API ID**: `case_study_text_panel`
 * - **Description**: CaseStudyTextPanel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSlice = prismic.SharedSlice<
  "case_study_text_panel",
  CaseStudyTextPanelSliceVariation
>;

/**
 * Item in *CompactHero → Default → Primary → CaseStudyContentFields*
 */
export interface CompactHeroSliceDefaultPrimaryCasestudycontentfieldsItem {}

/**
 * Primary content in *CompactHero → Default → Primary*
 */
export interface CompactHeroSliceDefaultPrimary {
  /**
   * hero_image field in *CompactHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: compact_hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * hero_title field in *CompactHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compact_hero.default.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * CaseStudyContentFields field in *CompactHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: compact_hero.default.primary.casestudycontentfields[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  casestudycontentfields: prismic.GroupField<
    Simplify<CompactHeroSliceDefaultPrimaryCasestudycontentfieldsItem>
  >;
}

/**
 * Default variation for CompactHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompactHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompactHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CompactHero*
 */
type CompactHeroSliceVariation = CompactHeroSliceDefault;

/**
 * CompactHero Shared Slice
 *
 * - **API ID**: `compact_hero`
 * - **Description**: CompactHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompactHeroSlice = prismic.SharedSlice<
  "compact_hero",
  CompactHeroSliceVariation
>;

/**
 * Item in *Contact → Default → Primary → contact info*
 */
export interface ContactSliceDefaultPrimaryContactInfoItem {
  /**
   * icon name field in *Contact → Default → Primary → contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * title field in *Contact → Default → Primary → contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Contact → Default → Primary → contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → office info*
 */
export interface ContactSliceDefaultPrimaryOfficeInfoItem {
  /**
   * days field in *Contact → Default → Primary → office info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_info[].days
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  days: prismic.KeyTextField;

  /**
   * hours field in *Contact → Default → Primary → office info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_info[].hours
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hours: prismic.KeyTextField;

  /**
   * is closed field in *Contact → Default → Primary → office info*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contact.default.primary.office_info[].is_closed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_closed: prismic.BooleanField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * main title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.main_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_title: prismic.RichTextField;

  /**
   * subtitle field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * contact us title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_us_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_us_title: prismic.RichTextField;

  /**
   * office hours title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_hours_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  office_hours_title: prismic.RichTextField;

  /**
   * form title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * contact info field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_info: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryContactInfoItem>
  >;

  /**
   * office info field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_info[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  office_info: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryOfficeInfoItem>
  >;

  /**
   * full name field label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.full_name_field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  full_name_field_label: prismic.KeyTextField;

  /**
   * email field label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email_field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_field_label: prismic.KeyTextField;

  /**
   * company field label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.company_field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_field_label: prismic.KeyTextField;

  /**
   * project budget label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.project_budget_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_budget_label: prismic.KeyTextField;

  /**
   * project goals label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.project_goals_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_goals_label: prismic.KeyTextField;

  /**
   * button label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * budget options field in *Contact → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.budget_options
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  budget_options: prismic.SelectField<
    | "Estimated Budget"
    | "I don't know yet"
    | "I'd rather not say"
    | "Less than £500"
    | "£1000 - £5000"
    | "£5000 - £10000"
    | "Above £10000"
  >;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * hero main heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_main_heading: prismic.RichTextField;

  /**
   * hero secondary heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_secondary_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_secondary_heading: prismic.RichTextField;

  /**
   * hero description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_description: prismic.KeyTextField;

  /**
   * button link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *WebsiteCard → Default → Primary → card*
 */
export interface WebsiteCardSliceDefaultPrimaryCardItem {
  /**
   * background image field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * title field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * link to website field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].link_to_website
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_to_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *WebsiteCard → Default → Primary*
 */
export interface WebsiteCardSliceDefaultPrimary {
  /**
   * card field in *WebsiteCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<WebsiteCardSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for WebsiteCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WebsiteCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WebsiteCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WebsiteCard*
 */
type WebsiteCardSliceVariation = WebsiteCardSliceDefault;

/**
 * WebsiteCard Shared Slice
 *
 * - **API ID**: `website_card`
 * - **Description**: WebsiteCard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WebsiteCardSlice = prismic.SharedSlice<
  "website_card",
  WebsiteCardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CaseStudyDocument,
      CaseStudyDocumentData,
      CaseStudySmDocument,
      CaseStudySmDocumentData,
      CaseStudySmDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBodyHerosectionSlicePrimary,
      HomepageDocumentDataBodyExpertisegroupSliceItem,
      HomepageDocumentDataBodyExpertiseareasSlicePrimary,
      HomepageDocumentDataBodyExpertiseareasSliceItem,
      HomepageDocumentDataBodyServiceGridSlicePrimary,
      HomepageDocumentDataBodyServiceGridSliceItem,
      HomepageDocumentDataBodyImageandtextSlicePrimary,
      HomepageDocumentDataBodyProcessSlicePrimary,
      HomepageDocumentDataBodyProcessSliceItem,
      HomepageDocumentDataBodyProjectShowcaseSlicePrimary,
      HomepageDocumentDataBodyProjectShowcaseSliceItem,
      HomepageDocumentDataBodyFaqSlicePrimary,
      HomepageDocumentDataBodyFaqSliceItem,
      HomepageDocumentDataBodySlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataHeaderNavigationItem,
      LayoutDocumentDataFooterQuickLinksItem,
      MainpageDocument,
      MainpageDocumentData,
      MainpageDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      TeamPageDocument,
      TeamPageDocumentData,
      TeamPageDocumentDataBodySlice,
      TeamPageDocumentDataBody1TeamHeroSlicePrimary,
      TeamPageDocumentDataBody1Slice,
      TeamPageDocumentDataBody2TeamMembersSliceItem,
      TeamPageDocumentDataBody2Slice,
      AllDocumentTypes,
      CaseStudyTextPanelSlice,
      CaseStudyTextPanelSliceDefaultPrimary,
      CaseStudyTextPanelSliceSolutionTextPanelPrimary,
      CaseStudyTextPanelSliceImpactTextPanelPrimary,
      CaseStudyTextPanelSliceVariation,
      CaseStudyTextPanelSliceDefault,
      CaseStudyTextPanelSliceSolutionTextPanel,
      CaseStudyTextPanelSliceImpactTextPanel,
      CompactHeroSlice,
      CompactHeroSliceDefaultPrimaryCasestudycontentfieldsItem,
      CompactHeroSliceDefaultPrimary,
      CompactHeroSliceVariation,
      CompactHeroSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimaryContactInfoItem,
      ContactSliceDefaultPrimaryOfficeInfoItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      WebsiteCardSlice,
      WebsiteCardSliceDefaultPrimaryCardItem,
      WebsiteCardSliceDefaultPrimary,
      WebsiteCardSliceVariation,
      WebsiteCardSliceDefault,
    };
  }
}
