// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AcademyDocumentDataSlicesSlice =
  | NavigationMenuSlice
  | PrivacyTextBoxSlice
  | HeroSlice
  | ProjectShowcaseSlice
  | ServiceGridSlice
  | ImageandtextSlice
  | ProcessSlice
  | FaqSlice
  | ExpertiseareasSlice;

/**
 * Content for Academy documents
 */
interface AcademyDocumentData {
  /**
   * Slice Zone field in *Academy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AcademyDocumentDataSlicesSlice> /**
   * Meta Title field in *Academy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: academy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Academy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: academy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Academy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: academy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Academy document from Prismic
 *
 * - **API ID**: `academy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AcademyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AcademyDocumentData>,
    "academy",
    Lang
  >;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
  /**
   * hero_image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * hero_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * challenge_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.challenge_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_title: prismic.RichTextField;

  /**
   * challenge_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.challenge_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_content: prismic.RichTextField;

  /**
   * solution_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.solution_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_title: prismic.RichTextField;

  /**
   * solution_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.solution_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_content: prismic.RichTextField;

  /**
   * impact_title field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.impact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_title: prismic.RichTextField;

  /**
   * impact_content field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.impact_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_content: prismic.RichTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

type CaseStudySmDocumentDataSlicesSlice =
  | CaseStudyTextPanelSlice
  | CompactHeroSlice;

/**
 * Content for Case Study SM documents
 */
interface CaseStudySmDocumentData {
  /**
   * Slice Zone field in *Case Study SM*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_sm.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CaseStudySmDocumentDataSlicesSlice> /**
   * Meta Title field in *Case Study SM*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: case_study_sm.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Case Study SM*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: case_study_sm.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Case Study SM*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_sm.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Case Study SM document from Prismic
 *
 * - **API ID**: `case_study_sm`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudySmDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CaseStudySmDocumentData>,
    "case_study_sm",
    Lang
  >;

type FilmDocumentDataSlicesSlice =
  | NavigationMenuSlice
  | FaqSlice
  | PrivacyTextBoxSlice
  | HeroSlice
  | ProcessSlice
  | ServiceGridSlice
  | ImageandtextSlice
  | ProjectShowcaseSlice
  | ExpertiseareasSlice;

/**
 * Content for Film documents
 */
interface FilmDocumentData {
  /**
   * Slice Zone field in *Film*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: film.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FilmDocumentDataSlicesSlice> /**
   * Meta Title field in *Film*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: film.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Film*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: film.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Film*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: film.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Film document from Prismic
 *
 * - **API ID**: `film`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FilmDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FilmDocumentData>, "film", Lang>;

type HomepageDocumentDataBodySlice =
  | NavigationMenuSlice
  | CompactHeroSlice
  | ExpertisegroupSlice
  | ExpertiseareasSlice
  | ServiceGridSlice
  | ImageandtextSlice
  | ProcessSlice
  | ProjectShowcaseSlice
  | FaqSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<HomepageDocumentDataBodySlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

interface LandingPageDocumentData {}

/**
 * Landing Page document from Prismic
 *
 * - **API ID**: `landing_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LandingPageDocumentData>,
    "landing_page",
    Lang
  >;

/**
 * Item in *Layout → header_navigation*
 */
export interface LayoutDocumentDataHeaderNavigationItem {
  /**
   * link_label field in *Layout → header_navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * link_object field in *Layout → header_navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[].link_object
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_object: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Layout → footer_quick_links*
 */
export interface LayoutDocumentDataFooterQuickLinksItem {
  /**
   * link_label field in *Layout → footer_quick_links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;

  /**
   * link_object field in *Layout → footer_quick_links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[].link_object
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_object: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * header_logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * header_cta_label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_cta_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  header_cta_label: prismic.KeyTextField;

  /**
   * header_cta_link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  header_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * header_navigation field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.header_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  header_navigation: prismic.GroupField<
    Simplify<LayoutDocumentDataHeaderNavigationItem>
  >;

  /**
   * footer_company_name field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_company_name: prismic.RichTextField;

  /**
   * footer_tagline field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_tagline: prismic.RichTextField;

  /**
   * footer_quick_links_title field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_quick_links_title: prismic.RichTextField;

  /**
   * footer_quick_links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_quick_links: prismic.GroupField<
    Simplify<LayoutDocumentDataFooterQuickLinksItem>
  >;

  /**
   * footer_contact_title field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_contact_title: prismic.RichTextField;

  /**
   * footer_email field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_email: prismic.KeyTextField;

  /**
   * footer_phone field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_phone: prismic.KeyTextField;

  /**
   * footer_address field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_address: prismic.RichTextField;

  /**
   * footer_copyright_text field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_copyright_text: prismic.RichTextField;

  /**
   * footer_privacy_policy_link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.footer_privacy_policy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_privacy_policy_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type MainpageDocumentDataSlicesSlice =
  | ProjectShowcaseSlice
  | NavigationMenuSlice
  | WebsiteCardSlice
  | ContactSlice
  | HeroSlice;

/**
 * Content for Mainpage documents
 */
interface MainpageDocumentData {
  /**
   * Slice Zone field in *Mainpage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MainpageDocumentDataSlicesSlice> /**
   * Meta Title field in *Mainpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: mainpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Mainpage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: mainpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Mainpage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Mainpage document from Prismic
 *
 * - **API ID**: `mainpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MainpageDocumentData>,
    "mainpage",
    Lang
  >;

type OurTeamPageDocumentDataSlicesSlice = NavigationMenuSlice | OurTeamSlice;

/**
 * Content for Our Team documents
 */
interface OurTeamPageDocumentData {
  /**
   * Slice Zone field in *Our Team*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<OurTeamPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Our Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: our_team_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Our Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: our_team_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Our Team*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Our Team document from Prismic
 *
 * - **API ID**: `our_team_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OurTeamPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<OurTeamPageDocumentData>,
    "our_team_page",
    Lang
  >;

type PrimaryNavigationDocumentDataSlicesSlice = NavigationMenuSlice;

/**
 * Content for Primary Navigation documents
 */
interface PrimaryNavigationDocumentData {
  /**
   * Slice Zone field in *Primary Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: primary_navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PrimaryNavigationDocumentDataSlicesSlice>;
}

/**
 * Primary Navigation document from Prismic
 *
 * - **API ID**: `primary_navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrimaryNavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrimaryNavigationDocumentData>,
    "primary_navigation",
    Lang
  >;

/**
 * Content for Privacy Policy documents
 */
interface PrivacyPolicyDocumentData {
  /**
   * title field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * page_content field in *Privacy Policy*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy.page_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_content: prismic.RichTextField;
}

/**
 * Privacy Policy document from Prismic
 *
 * - **API ID**: `privacy_policy`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicyDocumentData>,
    "privacy_policy",
    Lang
  >;

type PrivacyPolicySmDocumentDataSlicesSlice = PrivacyTextBoxSlice;

/**
 * Content for Privacy Policy SM documents
 */
interface PrivacyPolicySmDocumentData {
  /**
   * Slice Zone field in *Privacy Policy SM*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy_sm.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PrivacyPolicySmDocumentDataSlicesSlice> /**
   * Meta Title field in *Privacy Policy SM*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacy_policy_sm.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Privacy Policy SM*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacy_policy_sm.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Privacy Policy SM*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_policy_sm.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Privacy Policy SM document from Prismic
 *
 * - **API ID**: `privacy_policy_sm`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacyPolicySmDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PrivacyPolicySmDocumentData>,
    "privacy_policy_sm",
    Lang
  >;

type TabbDocumentDataSlicesSlice =
  | NavigationMenuSlice
  | FaqSlice
  | ProjectShowcaseSlice
  | ProcessSlice
  | ImageandtextSlice
  | ExpertiseareasSlice
  | ServiceGridSlice
  | HeroSlice
  | PrivacyTextBoxSlice;

/**
 * Content for Tabb documents
 */
interface TabbDocumentData {
  /**
   * Slice Zone field in *Tabb*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tabb.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TabbDocumentDataSlicesSlice> /**
   * Meta Title field in *Tabb*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tabb.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Tabb*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tabb.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Tabb*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tabb.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Tabb document from Prismic
 *
 * - **API ID**: `tabb`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TabbDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TabbDocumentData>, "tabb", Lang>;

type TeamPageDocumentDataBodySlice = never;

/**
 * Primary content in *Team Page → Slice zone → team_hero → Primary*
 */
export interface TeamPageDocumentDataBody1TeamHeroSlicePrimary {
  /**
   * Title field in *Team Page → Slice zone → team_hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main heading for the team page
   * - **API ID Path**: team_page.body1[].team_hero.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Team Page → Slice zone → team_hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Team page description paragraph
   * - **API ID Path**: team_page.body1[].team_hero.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Slice for *Team Page → Slice zone*
 */
export type TeamPageDocumentDataBody1TeamHeroSlice = prismic.Slice<
  "team_hero",
  Simplify<TeamPageDocumentDataBody1TeamHeroSlicePrimary>,
  never
>;

type TeamPageDocumentDataBody1Slice = TeamPageDocumentDataBody1TeamHeroSlice;

/**
 * Item content in *Team Page → Slice zone → team_members → Items*
 */
export interface TeamPageDocumentDataBody2TeamMembersSliceItem {
  /**
   * Name field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's full name
   * - **API ID Path**: team_page.body2[].team_members.items.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member's job title/position
   * - **API ID Path**: team_page.body2[].team_members.items.role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Image field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body2[].team_members.items.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Bio field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short biography or introduction
   * - **API ID Path**: team_page.body2[].team_members.items.bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Details field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed achievements/background (separate each point with a new line)
   * - **API ID Path**: team_page.body2[].team_members.items.details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;

  /**
   * LinkedIn URL field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: LinkedIn profile URL (optional)
   * - **API ID Path**: team_page.body2[].team_members.items.linkedin_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Twitter URL field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Twitter profile URL (optional)
   * - **API ID Path**: team_page.body2[].team_members.items.twitter_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  twitter_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * GitHub URL field in *Team Page → Slice zone → team_members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: GitHub profile URL (optional)
   * - **API ID Path**: team_page.body2[].team_members.items.github_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  github_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Slice for *Team Page → Slice zone*
 */
export type TeamPageDocumentDataBody2TeamMembersSlice = prismic.Slice<
  "team_members",
  Record<string, never>,
  Simplify<TeamPageDocumentDataBody2TeamMembersSliceItem>
>;

type TeamPageDocumentDataBody2Slice = TeamPageDocumentDataBody2TeamMembersSlice;

/**
 * Content for Team Page documents
 */
interface TeamPageDocumentData {
  /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  body: prismic.SliceZone<TeamPageDocumentDataBodySlice> /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body1[]
   * - **Tab**: Team Hero
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  body1: prismic.SliceZone<TeamPageDocumentDataBody1Slice> /**
   * Slice zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.body2[]
   * - **Tab**: Team Members
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  body2: prismic.SliceZone<TeamPageDocumentDataBody2Slice>;
}

/**
 * Team Page document from Prismic
 *
 * - **API ID**: `team_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeamPageDocumentData>,
    "team_page",
    Lang
  >;

export type AllDocumentTypes =
  | AcademyDocument
  | CaseStudyDocument
  | CaseStudySmDocument
  | FilmDocument
  | HomepageDocument
  | LandingPageDocument
  | LayoutDocument
  | MainpageDocument
  | OurTeamPageDocument
  | PrimaryNavigationDocument
  | PrivacyPolicyDocument
  | PrivacyPolicySmDocument
  | TabbDocument
  | TeamPageDocument;

/**
 * Primary content in *Expertiseareas → Default → Primary*
 */
export interface ExpertiseareasSliceDefaultPrimary {
  /**
   * heading field in *Expertiseareas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Expertiseareas → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;
}

/**
 * Primary content in *Expertiseareas → Items*
 */
export interface ExpertiseareasSliceDefaultItem {
  /**
   * icon_name field in *Expertiseareas → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * item_title field in *Expertiseareas → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * item_description field in *Expertiseareas → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertiseareas.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Default variation for Expertiseareas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseareasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExpertiseareasSliceDefaultPrimary>,
  Simplify<ExpertiseareasSliceDefaultItem>
>;

/**
 * Slice variation for *Expertiseareas*
 */
type ExpertiseareasSliceVariation = ExpertiseareasSliceDefault;

/**
 * Expertiseareas Shared Slice
 *
 * - **API ID**: `Expertiseareas`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseareasSlice = prismic.SharedSlice<
  "Expertiseareas",
  ExpertiseareasSliceVariation
>;

/**
 * Primary content in *Expertisegroup → Items*
 */
export interface ExpertisegroupSliceDefaultItem {
  /**
   * icon_name field in *Expertisegroup → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertisegroup.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * title field in *Expertisegroup → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertisegroup.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Expertisegroup → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Expertisegroup.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Expertisegroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertisegroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ExpertisegroupSliceDefaultItem>
>;

/**
 * Slice variation for *Expertisegroup*
 */
type ExpertisegroupSliceVariation = ExpertisegroupSliceDefault;

/**
 * Expertisegroup Shared Slice
 *
 * - **API ID**: `Expertisegroup`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertisegroupSlice = prismic.SharedSlice<
  "Expertisegroup",
  ExpertisegroupSliceVariation
>;

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * question field in *Faq → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Faq.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * answer field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Faq.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `Faq`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"Faq", FaqSliceVariation>;

/**
 * Primary content in *Herosection → Default → Primary*
 */
export interface HerosectionSliceDefaultPrimary {
  /**
   * hero_title_part1 field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.hero_title_part1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title_part1: prismic.RichTextField;

  /**
   * hero_title_part2 field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.hero_title_part2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title_part2: prismic.RichTextField;

  /**
   * hero_description field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * button_1_link field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.button_1_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * button_1_label field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.button_1_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_1_label: prismic.KeyTextField;

  /**
   * background_image field in *Herosection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Herosection.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Herosection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HerosectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HerosectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Herosection*
 */
type HerosectionSliceVariation = HerosectionSliceDefault;

/**
 * Herosection Shared Slice
 *
 * - **API ID**: `Herosection`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HerosectionSlice = prismic.SharedSlice<
  "Herosection",
  HerosectionSliceVariation
>;

/**
 * Primary content in *Imageandtext → Default → Primary*
 */
export interface ImageandtextSliceDefaultPrimary {
  /**
   * image field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *Imageandtext → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Imageandtext.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Imageandtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageandtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageandtextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Imageandtext*
 */
type ImageandtextSliceVariation = ImageandtextSliceDefault;

/**
 * Imageandtext Shared Slice
 *
 * - **API ID**: `Imageandtext`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageandtextSlice = prismic.SharedSlice<
  "Imageandtext",
  ImageandtextSliceVariation
>;

/**
 * Primary content in *Process → Default → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * title field in *Process → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Process → Items*
 */
export interface ProcessSliceDefaultItem {
  /**
   * icon_text field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].icon_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_text: prismic.KeyTextField;

  /**
   * item_title field in *Process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * weeks field in *Process → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].weeks
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  weeks: prismic.KeyTextField;

  /**
   * item_description field in *Process → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Process.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  Simplify<ProcessSliceDefaultItem>
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `Process`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSlice = prismic.SharedSlice<
  "Process",
  ProcessSliceVariation
>;

/**
 * Primary content in *ProjectShowcase → Default → Primary*
 */
export interface ProjectShowcaseSliceDefaultPrimary {
  /**
   * title field in *ProjectShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * section_id field in *ProjectShowcase → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *ProjectShowcase → Items*
 */
export interface ProjectShowcaseSliceDefaultItem {
  /**
   * project_image field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  project_image: prismic.ImageField<never>;

  /**
   * project_title field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_title: prismic.RichTextField;

  /**
   * project_description field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_description: prismic.RichTextField;

  /**
   * project_link field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].project_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * tags field in *ProjectShowcase → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ProjectShowcase.items[].tags
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tags: prismic.KeyTextField;
}

/**
 * Default variation for ProjectShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectShowcaseSliceDefaultPrimary>,
  Simplify<ProjectShowcaseSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectShowcase*
 */
type ProjectShowcaseSliceVariation = ProjectShowcaseSliceDefault;

/**
 * ProjectShowcase Shared Slice
 *
 * - **API ID**: `ProjectShowcase`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSlice = prismic.SharedSlice<
  "ProjectShowcase",
  ProjectShowcaseSliceVariation
>;

/**
 * Primary content in *ServiceGrid → Default → Primary*
 */
export interface ServiceGridSliceDefaultPrimary {
  /**
   * title field in *ServiceGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * columns field in *ServiceGrid → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 4
   * - **API ID Path**: ServiceGrid.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  columns: prismic.NumberField;

  /**
   * section_id field in *ServiceGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.default.primary.section_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_id: prismic.KeyTextField;
}

/**
 * Primary content in *ServiceGrid → Items*
 */
export interface ServiceGridSliceDefaultItem {
  /**
   * item_title field in *ServiceGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_title: prismic.RichTextField;

  /**
   * icon_name field in *ServiceGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * item_description field in *ServiceGrid → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;

  /**
   * icon_background_color field in *ServiceGrid → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: ServiceGrid.items[].icon_background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  icon_background_color: prismic.ColorField;
}

/**
 * Default variation for ServiceGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceGridSliceDefaultPrimary>,
  Simplify<ServiceGridSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceGrid*
 */
type ServiceGridSliceVariation = ServiceGridSliceDefault;

/**
 * ServiceGrid Shared Slice
 *
 * - **API ID**: `ServiceGrid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceGridSlice = prismic.SharedSlice<
  "ServiceGrid",
  ServiceGridSliceVariation
>;

/**
 * Primary content in *CaseStudyTextPanel → Challenge → Primary*
 */
export interface CaseStudyTextPanelSliceDefaultPrimary {
  /**
   * challenge_title field in *CaseStudyTextPanel → Challenge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.default.primary.challenge_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_title: prismic.RichTextField;

  /**
   * challenge_content field in *CaseStudyTextPanel → Challenge → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.default.primary.challenge_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge_content: prismic.RichTextField;
}

/**
 * Challenge variation for CaseStudyTextPanel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudyTextPanelSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CaseStudyTextPanel → Solution Text Panel → Primary*
 */
export interface CaseStudyTextPanelSliceSolutionTextPanelPrimary {
  /**
   * solution_title field in *CaseStudyTextPanel → Solution Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.solutionTextPanel.primary.solution_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_title: prismic.RichTextField;

  /**
   * solution_content field in *CaseStudyTextPanel → Solution Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.solutionTextPanel.primary.solution_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution_content: prismic.RichTextField;
}

/**
 * Solution Text Panel variation for CaseStudyTextPanel Slice
 *
 * - **API ID**: `solutionTextPanel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSliceSolutionTextPanel =
  prismic.SharedSliceVariation<
    "solutionTextPanel",
    Simplify<CaseStudyTextPanelSliceSolutionTextPanelPrimary>,
    never
  >;

/**
 * Primary content in *CaseStudyTextPanel → Impact Text Panel → Primary*
 */
export interface CaseStudyTextPanelSliceImpactTextPanelPrimary {
  /**
   * impact_title field in *CaseStudyTextPanel → Impact Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.impactTextPanel.primary.impact_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_title: prismic.RichTextField;

  /**
   * impact_content field in *CaseStudyTextPanel → Impact Text Panel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_text_panel.impactTextPanel.primary.impact_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact_content: prismic.RichTextField;
}

/**
 * Impact Text Panel variation for CaseStudyTextPanel Slice
 *
 * - **API ID**: `impactTextPanel`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSliceImpactTextPanel =
  prismic.SharedSliceVariation<
    "impactTextPanel",
    Simplify<CaseStudyTextPanelSliceImpactTextPanelPrimary>,
    never
  >;

/**
 * Slice variation for *CaseStudyTextPanel*
 */
type CaseStudyTextPanelSliceVariation =
  | CaseStudyTextPanelSliceDefault
  | CaseStudyTextPanelSliceSolutionTextPanel
  | CaseStudyTextPanelSliceImpactTextPanel;

/**
 * CaseStudyTextPanel Shared Slice
 *
 * - **API ID**: `case_study_text_panel`
 * - **Description**: CaseStudyTextPanel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudyTextPanelSlice = prismic.SharedSlice<
  "case_study_text_panel",
  CaseStudyTextPanelSliceVariation
>;

/**
 * Item in *CompactHero → Default → Primary → CaseStudyContentFields*
 */
export interface CompactHeroSliceDefaultPrimaryCasestudycontentfieldsItem {}

/**
 * Primary content in *CompactHero → Default → Primary*
 */
export interface CompactHeroSliceDefaultPrimary {
  /**
   * hero_image field in *CompactHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: compact_hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * hero_title field in *CompactHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compact_hero.default.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * CaseStudyContentFields field in *CompactHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: compact_hero.default.primary.casestudycontentfields[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  casestudycontentfields: prismic.GroupField<
    Simplify<CompactHeroSliceDefaultPrimaryCasestudycontentfieldsItem>
  >;
}

/**
 * Default variation for CompactHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompactHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompactHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CompactHero*
 */
type CompactHeroSliceVariation = CompactHeroSliceDefault;

/**
 * CompactHero Shared Slice
 *
 * - **API ID**: `compact_hero`
 * - **Description**: CompactHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompactHeroSlice = prismic.SharedSlice<
  "compact_hero",
  CompactHeroSliceVariation
>;

/**
 * Item in *Contact → Default → Primary → contact info*
 */
export interface ContactSliceDefaultPrimaryContactInfoItem {
  /**
   * icon name field in *Contact → Default → Primary → contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * title field in *Contact → Default → Primary → contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Contact → Default → Primary → contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Contact → Default → Primary → office info*
 */
export interface ContactSliceDefaultPrimaryOfficeInfoItem {
  /**
   * days field in *Contact → Default → Primary → office info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_info[].days
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  days: prismic.KeyTextField;

  /**
   * hours field in *Contact → Default → Primary → office info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_info[].hours
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hours: prismic.KeyTextField;

  /**
   * is closed field in *Contact → Default → Primary → office info*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contact.default.primary.office_info[].is_closed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_closed: prismic.BooleanField;
}

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * main title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.main_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_title: prismic.RichTextField;

  /**
   * subtitle field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * contact us title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_us_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_us_title: prismic.RichTextField;

  /**
   * office hours title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_hours_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  office_hours_title: prismic.RichTextField;

  /**
   * form title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  form_title: prismic.RichTextField;

  /**
   * contact info field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_info[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_info: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryContactInfoItem>
  >;

  /**
   * office info field in *Contact → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.office_info[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  office_info: prismic.GroupField<
    Simplify<ContactSliceDefaultPrimaryOfficeInfoItem>
  >;

  /**
   * full name field label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.full_name_field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  full_name_field_label: prismic.KeyTextField;

  /**
   * email field label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email_field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_field_label: prismic.KeyTextField;

  /**
   * company field label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.company_field_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_field_label: prismic.KeyTextField;

  /**
   * project budget label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.project_budget_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_budget_label: prismic.KeyTextField;

  /**
   * project goals label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.project_goals_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  project_goals_label: prismic.KeyTextField;

  /**
   * button label field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * budget options field in *Contact → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.budget_options
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  budget_options: prismic.SelectField<
    | "Estimated Budget"
    | "I don't know yet"
    | "I'd rather not say"
    | "Less than £500"
    | "£1000 - £5000"
    | "£5000 - £10000"
    | "Above £10000"
  >;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * hero main heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_main_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_main_heading: prismic.RichTextField;

  /**
   * hero secondary heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_secondary_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_secondary_heading: prismic.RichTextField;

  /**
   * hero description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_description: prismic.KeyTextField;

  /**
   * button link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * background image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *NavigationMenu → Default → Primary → menu*
 */
export interface NavigationMenuSliceDefaultPrimaryMenuItem {
  /**
   * link label field in *NavigationMenu → Default → Primary → menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.default.primary.menu[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_label: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *NavigationMenu → Default → Primary*
 */
export interface NavigationMenuSliceDefaultPrimary {
  /**
   * logo field in *NavigationMenu → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * menu field in *NavigationMenu → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.default.primary.menu[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu: prismic.GroupField<Simplify<NavigationMenuSliceDefaultPrimaryMenuItem>>;

  /**
   * cta label field in *NavigationMenu → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_menu.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Default variation for NavigationMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationMenuSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationMenuSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationMenu*
 */
type NavigationMenuSliceVariation = NavigationMenuSliceDefault;

/**
 * NavigationMenu Shared Slice
 *
 * - **API ID**: `navigation_menu`
 * - **Description**: NavigationMenu
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationMenuSlice = prismic.SharedSlice<
  "navigation_menu",
  NavigationMenuSliceVariation
>;

/**
 * Item in *OurTeam → Default → Primary → team member*
 */
export interface OurTeamSliceDefaultPrimaryTeamMemberItem {
  /**
   * headshot field in *OurTeam → Default → Primary → team member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.team_member[].headshot
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  headshot: prismic.ImageField<never>;

  /**
   * name field in *OurTeam → Default → Primary → team member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.team_member[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * role field in *OurTeam → Default → Primary → team member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.team_member[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * description field in *OurTeam → Default → Primary → team member*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.team_member[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *OurTeam → Default → Primary*
 */
export interface OurTeamSliceDefaultPrimary {
  /**
   * title field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * team member field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.default.primary.team_member[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  team_member: prismic.GroupField<
    Simplify<OurTeamSliceDefaultPrimaryTeamMemberItem>
  >;
}

/**
 * Default variation for OurTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurTeam*
 */
type OurTeamSliceVariation = OurTeamSliceDefault;

/**
 * OurTeam Shared Slice
 *
 * - **API ID**: `our_team`
 * - **Description**: OurTeam
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurTeamSlice = prismic.SharedSlice<
  "our_team",
  OurTeamSliceVariation
>;

/**
 * Primary content in *PrivacyTextBox → Default → Primary*
 */
export interface PrivacyTextBoxSliceDefaultPrimary {
  /**
   * title field in *PrivacyTextBox → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_text_box.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * page_content field in *PrivacyTextBox → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_text_box.default.primary.page_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_content: prismic.RichTextField;
}

/**
 * Default variation for PrivacyTextBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrivacyTextBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivacyTextBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivacyTextBox*
 */
type PrivacyTextBoxSliceVariation = PrivacyTextBoxSliceDefault;

/**
 * PrivacyTextBox Shared Slice
 *
 * - **API ID**: `privacy_text_box`
 * - **Description**: PrivacyTextBox
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrivacyTextBoxSlice = prismic.SharedSlice<
  "privacy_text_box",
  PrivacyTextBoxSliceVariation
>;

/**
 * Item in *WebsiteCard → Default → Primary → card*
 */
export interface WebsiteCardSliceDefaultPrimaryCardItem {
  /**
   * background image field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * title field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * primary description field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].primary_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_description: prismic.KeyTextField;

  /**
   * secondary description field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].secondary_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_description: prismic.KeyTextField;

  /**
   * link to website field in *WebsiteCard → Default → Primary → card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[].link_to_website
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_to_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *WebsiteCard → Default → Primary*
 */
export interface WebsiteCardSliceDefaultPrimary {
  /**
   * main title field in *WebsiteCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.main_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_title: prismic.RichTextField;

  /**
   * subtitle field in *WebsiteCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * card field in *WebsiteCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: website_card.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<WebsiteCardSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for WebsiteCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WebsiteCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WebsiteCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WebsiteCard*
 */
type WebsiteCardSliceVariation = WebsiteCardSliceDefault;

/**
 * WebsiteCard Shared Slice
 *
 * - **API ID**: `website_card`
 * - **Description**: WebsiteCard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WebsiteCardSlice = prismic.SharedSlice<
  "website_card",
  WebsiteCardSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AcademyDocument,
      AcademyDocumentData,
      AcademyDocumentDataSlicesSlice,
      CaseStudyDocument,
      CaseStudyDocumentData,
      CaseStudySmDocument,
      CaseStudySmDocumentData,
      CaseStudySmDocumentDataSlicesSlice,
      FilmDocument,
      FilmDocumentData,
      FilmDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataBodySlice,
      LandingPageDocument,
      LandingPageDocumentData,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataHeaderNavigationItem,
      LayoutDocumentDataFooterQuickLinksItem,
      MainpageDocument,
      MainpageDocumentData,
      MainpageDocumentDataSlicesSlice,
      OurTeamPageDocument,
      OurTeamPageDocumentData,
      OurTeamPageDocumentDataSlicesSlice,
      PrimaryNavigationDocument,
      PrimaryNavigationDocumentData,
      PrimaryNavigationDocumentDataSlicesSlice,
      PrivacyPolicyDocument,
      PrivacyPolicyDocumentData,
      PrivacyPolicySmDocument,
      PrivacyPolicySmDocumentData,
      PrivacyPolicySmDocumentDataSlicesSlice,
      TabbDocument,
      TabbDocumentData,
      TabbDocumentDataSlicesSlice,
      TeamPageDocument,
      TeamPageDocumentData,
      TeamPageDocumentDataBodySlice,
      TeamPageDocumentDataBody1TeamHeroSlicePrimary,
      TeamPageDocumentDataBody1Slice,
      TeamPageDocumentDataBody2TeamMembersSliceItem,
      TeamPageDocumentDataBody2Slice,
      AllDocumentTypes,
      ExpertiseareasSlice,
      ExpertiseareasSliceDefaultPrimary,
      ExpertiseareasSliceDefaultItem,
      ExpertiseareasSliceVariation,
      ExpertiseareasSliceDefault,
      ExpertisegroupSlice,
      ExpertisegroupSliceDefaultItem,
      ExpertisegroupSliceVariation,
      ExpertisegroupSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimary,
      FaqSliceDefaultItem,
      FaqSliceVariation,
      FaqSliceDefault,
      HerosectionSlice,
      HerosectionSliceDefaultPrimary,
      HerosectionSliceVariation,
      HerosectionSliceDefault,
      ImageandtextSlice,
      ImageandtextSliceDefaultPrimary,
      ImageandtextSliceVariation,
      ImageandtextSliceDefault,
      ProcessSlice,
      ProcessSliceDefaultPrimary,
      ProcessSliceDefaultItem,
      ProcessSliceVariation,
      ProcessSliceDefault,
      ProjectShowcaseSlice,
      ProjectShowcaseSliceDefaultPrimary,
      ProjectShowcaseSliceDefaultItem,
      ProjectShowcaseSliceVariation,
      ProjectShowcaseSliceDefault,
      ServiceGridSlice,
      ServiceGridSliceDefaultPrimary,
      ServiceGridSliceDefaultItem,
      ServiceGridSliceVariation,
      ServiceGridSliceDefault,
      CaseStudyTextPanelSlice,
      CaseStudyTextPanelSliceDefaultPrimary,
      CaseStudyTextPanelSliceSolutionTextPanelPrimary,
      CaseStudyTextPanelSliceImpactTextPanelPrimary,
      CaseStudyTextPanelSliceVariation,
      CaseStudyTextPanelSliceDefault,
      CaseStudyTextPanelSliceSolutionTextPanel,
      CaseStudyTextPanelSliceImpactTextPanel,
      CompactHeroSlice,
      CompactHeroSliceDefaultPrimaryCasestudycontentfieldsItem,
      CompactHeroSliceDefaultPrimary,
      CompactHeroSliceVariation,
      CompactHeroSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimaryContactInfoItem,
      ContactSliceDefaultPrimaryOfficeInfoItem,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      NavigationMenuSlice,
      NavigationMenuSliceDefaultPrimaryMenuItem,
      NavigationMenuSliceDefaultPrimary,
      NavigationMenuSliceVariation,
      NavigationMenuSliceDefault,
      OurTeamSlice,
      OurTeamSliceDefaultPrimaryTeamMemberItem,
      OurTeamSliceDefaultPrimary,
      OurTeamSliceVariation,
      OurTeamSliceDefault,
      PrivacyTextBoxSlice,
      PrivacyTextBoxSliceDefaultPrimary,
      PrivacyTextBoxSliceVariation,
      PrivacyTextBoxSliceDefault,
      WebsiteCardSlice,
      WebsiteCardSliceDefaultPrimaryCardItem,
      WebsiteCardSliceDefaultPrimary,
      WebsiteCardSliceVariation,
      WebsiteCardSliceDefault,
    };
  }
}
