export const lunaProcessingPhrases: string[] = [
  "Luna is thinking really hard 🌙",
  "Sprinkling a little magic on this ✨",
  "Hold on, Luna’s doing her thing",
  "Crunching thoughts… not snacks 🧠",
  "Connecting stars, one second ⭐",
  "Let me cook for a sec 🍳",
  "Summoning the right answer 🔮",
  "Thinking… but in a cool way",
  "Give me a heartbeat 💫",
  "Whispering to the servers 👀",
  "Making sense of the chaos",
  "Almost cracked it 🤞",
  "One tiny moon-moment 🌙",
  "Luna is plotting brilliance",
  "Processing… please enjoy the vibes",
  "Doing some behind-the-scenes wizardry",
  "Warming up the neurons 🔥",
  "Hold tight, magic loading",
  "Just lining the stars up",
  "Finishing touches ✨",
];
