// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  case_study_text_panel: dynamic(() => import("./CaseStudyTextPanel")),
  compact_hero: dynamic(() => import("./CompactHero")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  our_team: dynamic(() => import("./OurTeam")),
  website_card: dynamic(() => import("./WebsiteCard")),
};
