// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  Expertiseareas: dynamic(() => import("./Expertiseareas")),
  Expertisegroup: dynamic(() => import("./Expertisegroup")),
  Faq: dynamic(() => import("./Faq")),
  Imageandtext: dynamic(() => import("./Imageandtext")),
  Process: dynamic(() => import("./Process")),
  ProjectShowcase: dynamic(() => import("./ProjectShowcase")),
  ServiceGrid: dynamic(() => import("./ServiceGrid")),
  case_study_text_panel: dynamic(() => import("./CaseStudyTextPanel")),
  compact_hero: dynamic(() => import("./CompactHero")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  our_team: dynamic(() => import("./OurTeam")),
  website_card: dynamic(() => import("./WebsiteCard")),
};
